function cfg = configBlockedUEExperiment(updates)
%CONFIGBLOCKEDUEEXPERIMENT Single-UE study; legacy defaults remain separate.
if nargin<1, updates=struct(); end
base=struct('scenarioMode',"urbanStreetCanyon",'region',[0 500;0 500;0 45], ...
    'M',20,'K',80,'N_AP',4,'zAP',8,'zUE',1.5, ...
    'reflectionCoefficientMode',"fixed",'fixedReflectionMagnitude',0.6, ...
    'fixedReflectionPhaseDeg',0,'enablePathPruning',true, ...
    'minimumPathPowerDB',-160,'maximumNLoSPathsPerLink',Inf, ...
    'minBlockedUECount',5,'maxScenarioGenerationAttempts',10, ...
    'minimumTargetNLoSAPs',3,'targetBlockedUEIndex',[], ...
    'bandwidth',20e6,'targetRate',10e6,'thermalNoiseDensity',-174, ...
    'noiseFigure_dB',7,'maxTransmitPowerPerAP',1,'powerStep',0.05, ...
    'maxCandidateAPsForPowerSweep',4,'maxPowerCombinations',1e6, ...
    'numTopPowerSolutions',50,'verifyReproducibility',true, ...
    'resultsDir',fullfile(fileparts(mfilename('fullpath')),'blocked_ue_results'));
names=fieldnames(updates);
for i=1:numel(names), base.(names{i})=updates.(names{i}); end
cfg=configRayTracing3D(base);
positive={'bandwidth','targetRate','maxTransmitPowerPerAP','powerStep'};
for i=1:numel(positive)
    validateattributes(cfg.(positive{i}),{'numeric'},{'scalar','real','positive','finite'});
end
integers={'minBlockedUECount','maxScenarioGenerationAttempts','minimumTargetNLoSAPs', ...
    'maxCandidateAPsForPowerSweep','maxPowerCombinations','numTopPowerSolutions'};
for i=1:numel(integers)
    validateattributes(cfg.(integers{i}),{'numeric'},{'scalar','integer','positive','finite'});
end
assert(cfg.minimumTargetNLoSAPs>=2);
assert(cfg.minBlockedUECount<=cfg.K);
assert(cfg.fc==100e9,'This study requires a 100 GHz carrier.');
validateattributes(cfg.noiseFigure_dB,{'numeric'},{'scalar','real','finite'});
validateattributes(cfg.thermalNoiseDensity,{'numeric'},{'scalar','real','finite'});
end
